version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vanlog-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    environment:
      CHOKIDAR_USEPOLLING: "true"
    stdin_open: true
    tty: true
